alertmanager:
  enabled: true
  alertmanagerSpec:
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.19.0
    replicas: 1
    retention: 120h
coreDns:
  enabled: true
  service:
    port: 10054
    targetPort: 10054
    selector:
      k8s-app: kube-dns
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
kubelet:
  enabled: true
nodeExporter:
  enabled: true
prometheus:
  prometheusSpec:
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.12.0
    replicas: 2
    retention: 10d
    ruleSelector:
      app: prometheus
    serviceMonitorSelector:
      metrics: prometheus
kube-state-metrics:
  fullnameOverride: kube-state-metrics
prometheus-node-exporter:
  fullnameOverride: node-exporter
