apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "kore-aws-servicebroker"
  labels:
    kore: "cluster-app"
spec:
  selector:
    matchLabels:
      chart: aws-servicebroker-1.0.1
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
  assemblyPhase: "Pending"
  descriptor:
    version: "1.0.1"
    description: "AWS service broker"
    type: "aws-servicebroker"
